networks:
    Questify-dev:
        driver: bridge

volumes:
    Questify-postgres-data:
        name: Questify-postgres-data
    Questify-redis-data:
        name: Questify-redis-data
    Questify-storage:
        name: Questify-storage

services:
    app:
        build:
            context: ./environment/dev/app
            dockerfile: Dockerfile
            args:
                - INSTALL_XDEBUG=${DOCKER_INSTALL_XDEBUG:-true}
                - USER_ID=${DOCKER_HOST_USER_ID:-1000}
        container_name: Questify-app-dev
        working_dir: /application
        volumes:
            - ./environment/dev/app/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./environment/dev/app/php.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:ro
            - ./environment/dev/app/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf:ro
            - ./environment/dev/app/supervisord.conf:/etc/supervisor/custom-supervisord.conf:ro
            - .:/application
            - Questify-storage:/application/storage/app/public
        ports:
            - ${DOCKER_APP_HOST_PORT:-63851}:80
            - ${VITE_PORT}:5173
        networks:
            - Questify-dev
        restart: unless-stopped
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:16.3-alpine3.18@sha256:64e18e8fb3e9c9aac89ac590c5dd8306b862478404f76cd9b5f7720d012b4c47
        container_name: Questify-db-dev
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
            - PGDATA=/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready --dbname ${DB_DATABASE} --username ${DB_USERNAME}"]
            interval: 3s
            timeout: 3s
            retries: 5
        ports:
            - ${DOCKER_DATABASE_HOST_PORT:-63853}:5432
        volumes:
            - Questify-postgres-data:/var/lib/postgresql/data
        networks:
            - Questify-dev
        restart: unless-stopped

    mailpit:
      image: axllent/mailpit:v1.21.5@sha256:67143952f5f123692b922bced8ab2cea8947292576011a6b22d2cb2649dbcf78
      container_name: Questify-mailpit-dev
      networks:
        - Questify-dev
      ports:
        - ${DOCKER_MAILPIT_DASHBOARD_HOST_PORT:-63854}:8025
      restart: unless-stopped

    redis:
        image: redis:7.2.5-alpine3.19@sha256:8f157725f8eee31e65a8d4765f1f986d76aedc1a0503345dfb63a2b1b5a441ee
        container_name: Questify-redis-dev
        ports:
            - ${DOCKER_REDIS_HOST_PORT:-63852}:6379
        volumes:
            - Questify-redis-data:/data
        networks:
            - Questify-dev
        restart: unless-stopped
